spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiRecommendationService
      database: aiRecommendationService
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-recommendation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.aiservice.model.ActivityEvent
        spring.json.trusted.packages: '*'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8083